# Generated by Django 4.2.16 on 2024-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='area',
            field=models.IntegerField(choices=[(0, 'Near to fireplace'), (1, 'Terrace'), (2, 'Smoker'), (3, 'Inside'), (4, 'Second floor')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='have_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
