# Generated by Django 4.2.16 on 2024-12-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_how_many_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(default='', null=True),
        ),
    ]
