# Generated by Django 4.2.16 on 2024-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_special_request_alter_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
