# Generated by Django 4.2.16 on 2025-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
